apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: application3
  namespace: default
spec:
  releaseName: application3
  interval: 5m0s
  chart:
    spec:
      chart: ./charts/application3  # Relative path to the chart directory
      sourceRef:
        kind: GitRepository
        name: flux-system  # Matches the Git repository defined in Flux
        namespace: flux-system
  values:
    replicaCount: 2
    image:
      repository: enriquecatala/fastapi-helloworld
      tag: latest
    service:
      type: ClusterIP
      port: 5000

