apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: application3
  namespace: default
spec:
  releaseName: application3
  chart:
    spec:
      chart: ./charts/application3
  values:
    - ./values.yaml
