apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: application4
  namespace: default
spec:
  releaseName: application4
  interval: 5m0s
  chart:
    spec:
      chart: ./charts/application4  # Adjust the path accordingly
      sourceRef:
        kind: GitRepository
        name: flux-system  # Reference to the correct GitRepository in Flux
        namespace: flux-system
  values:
    replicaCount: 2
    image:
      repository: asdkant/fastapi-hello-world   
      tag: latest
    service:
      type: ClusterIP
      port: 80
